/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'james' at '1/8/17 4:13 AM' with Gradle 3.2.1
 *
 * @author james, @date 1/8/17 4:13 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
